#!/bin/bash
sbatch run_NrMmtc_SimPerScriptCampaign_RemArtigo2_cluster_deploymentScenario_JOB0_Sim_0.sh
sbatch run_NrMmtc_SimPerScriptCampaign_RemArtigo2_cluster_deploymentScenario_JOB0_Sim_1.sh
sbatch run_NrMmtc_SimPerScriptCampaign_RemArtigo2_cluster_deploymentScenario_JOB0_Sim_2.sh
sbatch run_NrMmtc_SimPerScriptCampaign_RemArtigo2_cluster_deploymentScenario_JOB0_Sim_3.sh
sbatch run_NrMmtc_SimPerScriptCampaign_RemArtigo2_cluster_deploymentScenario_JOB0_Sim_4.sh
sbatch run_NrMmtc_SimPerScriptCampaign_RemArtigo2_cluster_deploymentScenario_JOB0_Sim_5.sh
sbatch run_NrMmtc_SimPerScriptCampaign_RemArtigo2_cluster_deploymentScenario_JOB0_Sim_6.sh
sbatch run_NrMmtc_SimPerScriptCampaign_RemArtigo2_cluster_deploymentScenario_JOB0_Sim_7.sh
